name: CI/CD frontend dev

on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
  AWS_REGION: "eu-north-1"
  SOURCE_DIR: "dist"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build dist
        run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
